name: Build LLVM on Windows
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          choco install cmake ninja python3 --no-progress --force

      - name: Configure and Build LLVM
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -G Ninja ../llvm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="all" \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            -DLLVM_INSTALL_CMAKE=ON \
            -DLLVM_BUILD_TOOLS=ON \
            -DLLVM_BUILD_UTILS=ON \
            -DLLVM_BUILD_TESTS=OFF \
            -DLLVM_ENABLE_ASSERTIONS=OFF
          ninja

      - name: Upload Full Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-windows-full
          path: |
            build/
            llvm/
            clang/
