name: Build LLVM on Windows
on: [workflow_dispatch]

jobs:
  build-windows-native:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (CMake, Ninja)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install ninja --yes

      - name: Configure and Build LLVM
        run: |
          mkdir build
          cd build
          cmake -G Ninja ../llvm `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_ENABLE_PROJECTS="all" `
            -DLLVM_TARGETS_TO_BUILD="X86" `
            -DLLVM_BUILD_TOOLS=ON `
            -DLLVM_BUILD_UTILS=ON
            -DLLVM_ENABLE_ASSERTIONS=OFF
          ninja

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-windows-native
          path: |
            build/
            llvm/include/
            clang/include/
          compression-level: 0
